NAME = Account

SOURCES = Account.cpp tests.cpp
CC = c++
CPPFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SOURCES)

clean: 
	echo "Nothin to remove."

fclean: 
	rm -rf $(NAME)

re: fclean all
	